# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: libsql_client 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "libsql_client".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Hinegardner".freeze]
  s.date = "2023-05-13"
  s.description = "LibsqlClient is the Ruby library to the libSQL sqld server (including Turso).".freeze
  s.email = "jeremy@copiousfreetime.org".freeze
  s.files = ["".freeze]
  s.homepage = "http://github.com/copiousfreetime/libsql-client-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README.md".freeze, "--markup".freeze, "tomdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.3.0".freeze)
  s.rubygems_version = "3.4.10".freeze
  s.summary = "LibsqlClient is the Ruby library to the libSQL sqld server (including Turso).".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<rake>.freeze, ["~> 13.0"])
  s.add_development_dependency(%q<minitest>.freeze, ["~> 5.17"])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.4"])
  s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.21"])
end
